### ISSUE TITLE
Issue with calibrate.py

### ISSUE THREAD

**Issue by rockybeachradio** [leocurrie/ledserver#1]
Hello Leocurrie,
thank you for your great work with the ChristmasTree.
I am trying build, based on your code and need your help.
Thank you in advance.

Until now i managed to go the MJG-Streamer on a RaspberryPy-ZeroW and the ESP8266 working.
But I have an issue with the calibrate.py and i hope you can help me fixing it.
I adapted the following lines in the calibrate.py:
     # POST the data to the server
     req = urllib2.Request('http://192.168.1.129:2390/pixels')
     req.add_header('Content-Type', 'application/json')
     response = urllib2.urlopen(req, json.dumps(data))

192.168.1.129 it the IP address of my ESP8266
The Port 2390 was defined in your PixelServer.ino, so I adapted it

When I execute it in the commandline "python calibrate.py" the following error message shows up in the terminal:
var pixels = [
Traceback (most recent call last):
File "calibrate.py", line 26, in
response = urllib2.urlopen(req, json.dumps(data))
File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
return opener.open(url, data, timeout)
File "/usr/lib/python2.7/urllib2.py", line 429, in open
response = self._open(req, data)
File "/usr/lib/python2.7/urllib2.py", line 447, in _open
'_open', req)
File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
result = func(*args)
File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
return self.do_open(httplib.HTTPConnection, req)
File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
raise URLError(err)
urllib2.URLError: <urlopen error [Errno 111] Connection refused>

When I delete the "response = urllib2.urlopen(req, json.dumps(data))" command, the script runs without an error.
The ESP8266 is connected to my WiFi network and responds to ping.

What is going wrong?

Best, Andreas

**Comment by rockybeachradio** [comment]
Solved it.
Solution: changed core to use "socket" instead of urllib.
